##############################################
# Example config for ACMGA pipeline Snakefile  #
##############################################

########################
# REQUIRED PARAMETERS  #
########################


#Collection of input fasta file names.
fasta:
  [
  
   'An-1.chr.all.v2.0.fasta',
   'Cvi.chr.all.v2.0.fasta',
   'Arabidopsis_thaliana.TAIR10.dna.toplevel.fa',
   'Ler.chr.all.v2.0.fasta'
  ]

#1、Collection of gff file names corresponding to input fasta files
#2、Collection of gff file names for the ancestral sequence (N0.gff~N∞.gff) ( with the .gff suffix).
gff:
  ['Cvi.protein-coding.genes.v2.5.2019-10-09.gff3',
   'An-1.protein-coding.genes.v2.5.2019-10-09.gff3',
   'Ler.protein-coding.genes.v2.5.2019-10-09.gff3',
   'Arabidopsis_thaliana.TAIR10.56.gff3',
   'N0.gff3',
   'N1.gff3',
   'N2.gff3',
  ]

# fsata and gff species name
# The species names should each match a fasta file and gff file in "ACMGA/data"
species:
  [
       'Cvi',
       'An-1',
       'Ler',
       'Arabidopsis_thaliana',
  ]

#In the guide tree (Ler.protein:0.00493038,(Cvi.protein:0.0145906,(Arabidopsis_thaliana.protein:0.0117518,An-1.protein:0.00833626)N2:0.0070939)N1:0.00493038)N0;,
#the names of ancestral nodes are:'N0','N1','N2'
ancestor:
  [
     'N0',
     'N1',
     'N2',
 ]

#The paths where the GFF file, FASTA file are located.
PATH:
    'data/Arabidopsis/'

#The path of collection of CDS files
nonDuplicateCDS:
    'data/data/non_duplicate_CDS.fa'



#The path of guide tree
Tree:
    'data/fourevolverPlant.txt'

#The XML file required for the ACMGA to run.
XML:
    'workflow/envs/cactus_progressive_config.xml'

#The default parameters of minimap in ACMGA, it is recommended to use the default parameters.
minimap2ForGff:
  " -x splice -t 10 -k 12 -a -p 0.4 -N 20 "
minimap2Paramters:
  " -x splice -t 35 -k 12 -a -p 0.4 -N 20 "

#The configuration parameters for the proali command in AnchorWave, where -t specifies the number of threads.

proaliParamters:
  " -Q 1 -R 1 -t 10  "

#The configuration parameters for the genoali command in AnchorWave, where -t specifies the number of threads.
genoaliParamters:
  " -t 5 -IV "

#The number of threads used to run the cactus part
cactus_threads:
  "--t 36"

#This mode can choose "docker" or "local", which needs to affect the paths of some commands in the generated command.sh.
model:
  "docker"
  #"local"
