fasta:
  ['Sha.chr.all.v2.0.fasta',
   'Kyo.chr.all.v2.0.fasta',
   'An-1.chr.all.v2.0.fasta',
   'Cvi.chr.all.v2.0.fasta',
   'C24.chr.all.v2.0.fasta',
   'Arabidopsis_thaliana.TAIR10.dna.toplevel.fa',
   'Eri.chr.all.v2.0.fasta',
   'Ler.chr.all.v2.0.fasta'
  ]

gff:
  ['Cvi.protein-coding.genes.v2.5.2019-10-09.gff3',
   'Eri.protein-coding.genes.v2.5.2019-10-09.gff3',
   'Kyo.protein-coding.genes.v2.5.2019-10-09.gff3',
   'An-1.protein-coding.genes.v2.5.2019-10-09.gff3',
   'C24.protein-coding.genes.v2.5.2019-10-09.gff3',
   'Sha.protein-coding.genes.v2.5.2019-10-09.gff3',
   'Ler.protein-coding.genes.v2.5.2019-10-09.gff3',
   'Arabidopsis_thaliana.TAIR10.56.gff3',
   'N0.gff',
   'N1.gff',
   'N2.gff',
   'N3.gff',
   'N4.gff',
   'N5.gff',
   'N6.gff',



  ]


species:
  [
       'Cvi',
       'Eri',
       'Kyo',
       'An-1',
       'C24',
       'Sha',
       'Ler',
       'Arabidopsis_thaliana',
  ]
ancestor:
  [
     'N0',
     'N1',
     'N2',
     'N3',
     'N4',
     'N5',
     'N6',
 ]

PATH:
    '/data/SlurmArabidopsis/'
XML:
    'data/cactus_progressive_config.xml'
Tree:
    'data/SlurmArabidopsis/examples.txt'
uniqueCds:
    'data/SlurmArabidopsis/unique.fa'
minimap2ForGff:
  " -x splice -t 10 -k 12 -a -p 0.4 -N 20 "
minimap2Paramters:
  " -x splice -t 35 -k 12 -a -p 0.4 -N 20 "
proaliParamters:
  " -Q 1 -R 1 -t 10  "
genoaliParamters:
  " -t 5 -IV "